import { Notification, ChatRoom, ChatMessage, AIRecommendation, Goal, TeamMember, CalendarEvent } from "@/redesign/app/lib/types";

// 알림 Mock 데이터
export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    type: "application_approved",
    title: "오피스아워 신청이 승인되었습니다",
    content: "'마케팅 전략 컨설팅' 신청이 승인되었습니다. 2026년 2월 12일 14:00에 진행됩니다.",
    link: "/application/app1",
    isRead: false,
    createdAt: new Date("2026-02-08T09:30:00"),
    userId: "user1",
    relatedId: "app1",
    priority: "high",
  },
  {
    id: "notif2",
    type: "message",
    title: "새 메시지가 도착했습니다",
    content: "김컨설턴트님이 메시지를 보냈습니다: '안녕하세요, 미팅 자료 검토 완료했습니다.'",
    link: "/messages",
    isRead: false,
    createdAt: new Date("2026-02-08T08:15:00"),
    userId: "user1",
    relatedId: "msg1",
    priority: "medium",
  },
  {
    id: "notif3",
    type: "report_reminder",
    title: "보고서 작성 알림",
    content: "1월 31일에 진행한 오피스아워 보고서를 작성해주세요. (7일 경과)",
    link: "/pending-reports",
    isRead: false,
    createdAt: new Date("2026-02-07T10:00:00"),
    userId: "user1",
    relatedId: "app10",
    priority: "high",
  },
  {
    id: "notif4",
    type: "meeting_upcoming",
    title: "내일 미팅이 예정되어 있습니다",
    content: "'재무 전략 컨설팅' 세션이 내일 오전 10시에 시작됩니다.",
    link: "/unified-calendar",
    isRead: true,
    createdAt: new Date("2026-02-06T16:00:00"),
    userId: "user1",
    relatedId: "app2",
    priority: "medium",
  },
  {
    id: "notif5",
    type: "consultant_assigned",
    title: "컨설턴트가 배정되었습니다",
    content: "비정기 오피스아워에 이전문 컨설턴트가 배정되었습니다.",
    link: "/application/app3",
    isRead: true,
    createdAt: new Date("2026-02-05T14:30:00"),
    userId: "user1",
    relatedId: "app3",
    priority: "low",
  },
];

// 채팅방 Mock 데이터
export const mockChatRooms: ChatRoom[] = [
  {
    id: "room1",
    name: "김컨설턴트",
    type: "direct",
    participants: ["user1", "consultant1"],
    lastMessage: {
      id: "msg1",
      chatRoomId: "room1",
      senderId: "consultant1",
      senderName: "김컨설턴트",
      content: "안녕하세요, 미팅 자료 검토 완료했습니다. 추가로 논의할 부분이 있어 연락드립니다.",
      attachments: [],
      isRead: false,
      createdAt: new Date("2026-02-08T08:15:00"),
    },
    unreadCount: 2,
    createdAt: new Date("2026-01-15T10:00:00"),
    updatedAt: new Date("2026-02-08T08:15:00"),
    applicationId: "app1",
  },
  {
    id: "room2",
    name: "이전문 컨설턴트",
    type: "direct",
    participants: ["user1", "consultant2"],
    lastMessage: {
      id: "msg2",
      chatRoomId: "room2",
      senderId: "user1",
      senderName: "임팩트 스타트업",
      content: "네, 자료 전달 감사합니다!",
      attachments: [],
      isRead: true,
      createdAt: new Date("2026-02-07T15:30:00"),
    },
    unreadCount: 0,
    createdAt: new Date("2026-01-20T14:00:00"),
    updatedAt: new Date("2026-02-07T15:30:00"),
  },
  {
    id: "room3",
    name: "고객 지원팀",
    type: "support",
    participants: ["user1", "staff1"],
    lastMessage: {
      id: "msg3",
      chatRoomId: "room3",
      senderId: "staff1",
      senderName: "고객지원팀",
      content: "문의하신 내용에 대해 답변드립니다.",
      attachments: [],
      isRead: true,
      createdAt: new Date("2026-02-06T11:00:00"),
    },
    unreadCount: 0,
    createdAt: new Date("2026-01-10T09:00:00"),
    updatedAt: new Date("2026-02-06T11:00:00"),
  },
];

// 채팅 메시지 Mock 데이터
export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg1_1",
    chatRoomId: "room1",
    senderId: "consultant1",
    senderName: "김컨설턴트",
    content: "안녕하세요, 다음 주 화요일 미팅 준비를 위해 몇 가지 자료를 미리 보내드립니다.",
    attachments: [],
    isRead: true,
    createdAt: new Date("2026-02-07T14:00:00"),
  },
  {
    id: "msg1_2",
    chatRoomId: "room1",
    senderId: "user1",
    senderName: "임팩트 스타트업",
    content: "감사합니다! 미리 검토해보겠습니다.",
    attachments: [],
    isRead: true,
    createdAt: new Date("2026-02-07T14:15:00"),
  },
  {
    id: "msg1_3",
    chatRoomId: "room1",
    senderId: "consultant1",
    senderName: "김컨설턴트",
    content: "안녕하세요, 미팅 자료 검토 완료했습니다. 추가로 논의할 부분이 있어 연락드립니다.",
    attachments: [
      {
        id: "att1",
        name: "미팅_준비자료.pdf",
        url: "#",
        type: "document",
        size: 1024000,
      },
    ],
    isRead: false,
    createdAt: new Date("2026-02-08T08:15:00"),
  },
];

// AI 추천 Mock 데이터
export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: "rec1",
    type: "consultant",
    title: "마케팅 전문 컨설턴트 추천",
    description: "현재 매출 성장률을 고려할 때 마케팅 전략 수립이 필요합니다.",
    reason: "최근 3개월간 매출이 15% 성장했으나, 고객 획득 비용이 증가하는 추세입니다. 마케팅 ROI 개선을 위한 전문가 조언이 필요한 시점입니다.",
    confidence: 92,
    relatedData: {
      consultantId: "consultant3",
    },
    createdAt: new Date("2026-02-08T00:00:00"),
    isApplied: false,
  },
  {
    id: "rec2",
    type: "topic",
    title: "투자 유치 IR 자료 준비",
    description: "다음 분기 투자 유치를 목표로 IR 자료를 준비하세요.",
    reason: "현재 성장 지표가 우수하며, Pre-A 라운드 투자 유치에 적합한 시기입니다. 3개월 내 IR 자료를 준비하면 성공 가능성이 높습니다.",
    confidence: 87,
    relatedData: {
      expectedAmount: 1500000000,
      targetInvestors: ["벤처캐피탈 A", "임팩트 투자사 B"],
    },
    createdAt: new Date("2026-02-07T00:00:00"),
    isApplied: false,
  },
  {
    id: "rec3",
    type: "timing",
    title: "오피스아워 신청 최적 시기",
    description: "다음 주 화요일 오전이 승인 확률이 가장 높습니다.",
    reason: "통계 분석 결과, 화요일 오전에 신청한 경우 평균 승인 시간이 2.3시간으로 가장 빠르며, 승인률도 95%로 높습니다.",
    confidence: 78,
    relatedData: {
      optimalTime: "2026-02-11T10:00:00",
      averageApprovalTime: "2.3시간",
    },
    createdAt: new Date("2026-02-06T00:00:00"),
    isApplied: false,
  },
  {
    id: "rec4",
    type: "partnership",
    title: "유사 기업과의 협업 기회",
    description: "같은 프로그램의 '그린테크'와 협업 가능성이 있습니다.",
    reason: "두 기업 모두 ESG 분야에서 활동하며, 상호 보완적인 기술을 보유하고 있습니다. 협업 시 시너지 효과가 클 것으로 예상됩니다.",
    confidence: 81,
    relatedData: {
      companyName: "그린테크",
      synergy: ["기술 협력", "공동 마케팅", "고객 공유"],
    },
    createdAt: new Date("2026-02-05T00:00:00"),
    isApplied: false,
  },
];

// 목표 Mock 데이터
export const mockGoals: Goal[] = [
  {
    id: "goal1",
    title: "Q1 매출 목표 5억원 달성",
    description: "1분기 목표 매출 5억원 달성을 위한 마케팅 및 영업 활동 강화",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-03-31",
    assignees: ["user1"],
    tags: ["매출", "Q1", "우선순위"],
    progress: 65,
    createdAt: new Date("2026-01-01T00:00:00"),
    updatedAt: new Date("2026-02-08T00:00:00"),
    createdBy: "user1",
    comments: [
      {
        id: "comment1",
        goalId: "goal1",
        userId: "user1",
        userName: "임팩트 스타트업",
        content: "현재 3.2억원 달성. 목표 대비 64% 진행 중",
        createdAt: new Date("2026-02-07T10:00:00"),
      },
    ],
  },
  {
    id: "goal2",
    title: "신규 직원 3명 채용",
    description: "개발팀 2명, 마케팅팀 1명 채용 완료",
    status: "review",
    priority: "high",
    dueDate: "2026-02-28",
    assignees: ["user1"],
    tags: ["채용", "팀 확장"],
    progress: 85,
    createdAt: new Date("2026-01-15T00:00:00"),
    updatedAt: new Date("2026-02-06T00:00:00"),
    createdBy: "user1",
  },
  {
    id: "goal3",
    title: "B Corp 인증 신청",
    description: "B Corporation 인증 신청서 제출 및 심사 진행",
    status: "todo",
    priority: "medium",
    dueDate: "2026-04-30",
    assignees: ["user1"],
    tags: ["인증", "ESG"],
    progress: 20,
    createdAt: new Date("2026-02-01T00:00:00"),
    updatedAt: new Date("2026-02-05T00:00:00"),
    createdBy: "user1",
  },
  {
    id: "goal4",
    title: "특허 1건 출원",
    description: "AI 기반 임팩트 측정 알고리즘 특허 출원",
    status: "completed",
    priority: "high",
    dueDate: "2026-02-15",
    assignees: ["user1"],
    tags: ["특허", "기술"],
    progress: 100,
    createdAt: new Date("2026-01-10T00:00:00"),
    updatedAt: new Date("2026-02-10T00:00:00"),
    createdBy: "user1",
  },
  {
    id: "goal5",
    title: "고객 만족도 조사 실시",
    description: "기존 고객 대상 만족도 조사 및 피드백 수집",
    status: "backlog",
    priority: "low",
    dueDate: "2026-05-31",
    assignees: ["user1"],
    tags: ["고객", "피드백"],
    progress: 0,
    createdAt: new Date("2026-02-05T00:00:00"),
    updatedAt: new Date("2026-02-05T00:00:00"),
    createdBy: "user1",
  },
];

// 팀 멤버 Mock 데이터
export const mockTeamMembers: TeamMember[] = [
  {
    id: "user1",
    email: "ceo@impactstartup.com",
    companyName: "임팩트 스타트업",
    programName: "소셜벤처 육성 프로그램",
    programs: ["prog1"],
    role: "admin",
    position: "대표이사",
    department: "경영진",
    joinedAt: new Date("2025-01-15T00:00:00"),
    isActive: true,
    permissions: {
      canApplyRegular: true,
      canApplyIrregular: true,
      canViewAll: true,
      managedPrograms: ["prog1"],
    },
    createdAt: new Date("2025-01-15T00:00:00"),
    lastLoginAt: new Date("2026-02-08T09:00:00"),
    status: "active",
  },
  {
    id: "user2",
    email: "cto@impactstartup.com",
    companyName: "김기술",
    programName: "소셜벤처 육성 프로그램",
    programs: ["prog1"],
    role: "user",
    position: "CTO",
    department: "기술",
    joinedAt: new Date("2025-03-01T00:00:00"),
    isActive: true,
    permissions: {
      canApplyRegular: true,
      canApplyIrregular: false,
      canViewAll: false,
    },
    createdAt: new Date("2025-03-01T00:00:00"),
    lastLoginAt: new Date("2026-02-07T18:30:00"),
    status: "active",
  },
  {
    id: "user3",
    email: "cmo@impactstartup.com",
    companyName: "박마케팅",
    programName: "소셜벤처 육성 프로그램",
    programs: ["prog1"],
    role: "user",
    position: "CMO",
    department: "마케팅",
    joinedAt: new Date("2025-06-15T00:00:00"),
    isActive: true,
    permissions: {
      canApplyRegular: true,
      canApplyIrregular: false,
      canViewAll: false,
    },
    createdAt: new Date("2025-06-15T00:00:00"),
    lastLoginAt: new Date("2026-02-06T14:20:00"),
    status: "active",
  },
];
