window.AX_DASHBOARD_DATA = {
  meta: {
    title: "AX Orchestrate Dashboard",
    subtitle: "GitHub/GitGantt, AXR 변화이론, Codex 사용량을 한 화면에서 보는 비개발자용 운영판",
    period: "2026-04-23 ~ 2026-05-14",
    updatedAt: "2026-04-24T14:20:00+09:00",
    updateMode: "로컬 CLI 수동 업데이트",
    source: "AXR Weekly Report 20260417, GitHub issues #56-#76",
  },
  impact: {
    label: "Impact",
    title: "혁신을 위한 AI혁신기업",
    summary:
      "기능 수를 늘리는 것보다 운영 가능성과 제품 구조를 정리해, 실제 업무 전환이 가능한 AX 체계를 만든다.",
  },
  outcomes: [
    {
      id: "productivity",
      label: "Outcome 1",
      title: "생산성 강화 및 업무 표준화",
      shortOutcome: "업무효율화, 수작업 오류와 비용 최소화",
    },
    {
      id: "data-assets",
      label: "Outcome 2",
      title: "데이터 자산화",
      shortOutcome: "스타트업 데이터와 내부 지식 데이터 축적",
    },
    {
      id: "ax-foundation",
      label: "Outcome 3",
      title: "AX를 위한 기초 인프라",
      shortOutcome: "AX 기반 기능, 리스크관리, 역량강화",
    },
  ],
  outputs: [
    {
      id: "company-growth-platform",
      name: "기업육성 플랫폼",
      outcome: "data-assets",
      stage: "D",
      status: "배포/전환",
      currentActivity: "오피스아워 TF 의견 반영",
      nextActivity: "정책 설계와 QA 반영",
      linkedWorkItems: ["github-56"],
    },
    {
      id: "project-platform",
      name: "사업관리 플랫폼",
      outcome: "productivity",
      stage: "D",
      status: "배포/전환",
      currentActivity: "PM과 어드민 핵심 데이터 흐름 안정화",
      nextActivity: "사업 등록 체크리스트와 Admin 사이클 정리",
      linkedWorkItems: [],
    },
    {
      id: "ppt-archive",
      name: "PPT 아카이브",
      outcome: "ax-foundation",
      stage: "A",
      status: "내부 검증",
      currentActivity: "테스트 배포 완료",
      nextActivity: "업로드/페이지별 파싱과 로딩 안정화",
      linkedWorkItems: [],
    },
    {
      id: "hwp-editor",
      name: "HWP 에디터",
      outcome: "ax-foundation",
      stage: "A",
      status: "내부 검증",
      currentActivity: "이력서 기능 테스트 완료",
      nextActivity: "이력서 자동화 안정화",
      linkedWorkItems: [],
    },
    {
      id: "pdf-image-analysis",
      name: "PDF/이미지 분석",
      outcome: "ax-foundation",
      stage: "A",
      status: "내부 검증",
      currentActivity: "테스트 배포 완료",
      nextActivity: "적격/정산 대응 모듈화 논의",
      linkedWorkItems: [],
    },
  ],
  workItems: [
    {
      id: "github-56",
      issueNumber: 56,
      title: "정기 오피스아워 일정 선택 및 확정 연동 고도화",
      plainTitle: "정기 오피스아워 전체 일정/확정 흐름 정리",
      type: "epic",
      group: "오피스아워",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "D",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "정책, 스토리, 세부 Task 진행률을 한 번에 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/56",
    },
    {
      id: "github-64",
      issueNumber: 64,
      title: "대상 범위 고정 (정기만 포함, 비정기 제외)",
      plainTitle: "이번 범위는 정기 오피스아워만 포함",
      type: "policy",
      group: "정책 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "B",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "비정기 오피스아워 제외 기준 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/64",
    },
    {
      id: "github-65",
      issueNumber: 65,
      title: "신청 가능 요일 고정 (화요일/목요일)",
      plainTitle: "신청 가능 요일을 화요일/목요일로 고정",
      type: "policy",
      group: "정책 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "B",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "요일 정책을 화면/운영 문구에 맞춤",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/65",
    },
    {
      id: "github-66",
      issueNumber: 66,
      title: "세션 형식 유지 (온라인/오프라인)",
      plainTitle: "온라인/오프라인 세션 형식을 유지",
      type: "policy",
      group: "정책 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "B",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "세션 형식별 안내 문구 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/66",
    },
    {
      id: "github-67",
      issueNumber: 67,
      title: "일정 연동 범위 고정 (Calendar/Gmail/Meet)",
      plainTitle: "확정 후 Calendar/Gmail/Meet 연동 범위 고정",
      type: "policy",
      group: "정책 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "B",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "확정 후 어떤 알림과 일정이 나가는지 정리",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/67",
    },
    {
      id: "github-68",
      issueNumber: 68,
      title: "대기 상태 처리 고정 (신청 접수 즉시 슬롯 잠금)",
      plainTitle: "신청 접수 직후 대기 상태와 슬롯 잠금",
      type: "policy",
      group: "대기/잠금",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "B",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "기업/관리자/컨설턴트 화면 상태명 통일",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/68",
    },
    {
      id: "github-69",
      issueNumber: 69,
      title: "자동 확정 처리 고정 (72시간 내 미거절 시 확정)",
      plainTitle: "72시간 내 미거절 신청은 자동 확정",
      type: "policy",
      group: "자동 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "B",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "기준 시점과 후속 연동 조건 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/69",
    },
    {
      id: "github-57",
      issueNumber: 57,
      title: "정기 오피스아워 신청 진입 및 일정 선택 흐름 정리",
      plainTitle: "신청 시작부터 일정 선택까지 흐름 정리",
      type: "story",
      group: "일정 선택",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "정기 신청 진입점과 안내 문구 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/57",
    },
    {
      id: "github-58",
      issueNumber: 58,
      title: "날짜/시간 선택 정책 반영 (화요일·목요일 고정)",
      plainTitle: "화/목만 선택되는 일정 정책 반영",
      type: "story",
      group: "일정 선택",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "선택 가능한 날짜만 보이도록 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/58",
    },
    {
      id: "github-59",
      issueNumber: 59,
      title: "신청 접수 이후 상태 관리",
      plainTitle: "신청 후 상태가 일관되게 보이도록 정리",
      type: "story",
      group: "대기/잠금",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "수락 대기 상태와 취소 가능 조건 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/59",
    },
    {
      id: "github-60",
      issueNumber: 60,
      title: "정기 오피스아워 날짜/시간 선택 정책 반영",
      plainTitle: "선택 가능한 시간과 제출 전 재확인",
      type: "story",
      group: "일정 선택",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "제출 직전 가능 시간 재확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/60",
    },
    {
      id: "github-61",
      issueNumber: 61,
      title: "일정 확정 이후 Calendar/Gmail/Meet 연동",
      plainTitle: "확정 일정의 캘린더/메일/미팅 연결",
      type: "story",
      group: "외부 연동",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "수동/자동 확정 후 동일한 연동 품질 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/61",
    },
    {
      id: "github-62",
      issueNumber: 62,
      title: "일정 변경/취소 후 후속 반영",
      plainTitle: "변경/취소 후 상태와 연동 정보 갱신",
      type: "story",
      group: "외부 연동",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "변경/취소 시 알림과 일정 정리",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/62",
    },
    {
      id: "github-63",
      issueNumber: 63,
      title: "비정기 오피스아워 비노출 및 핵심 시나리오 QA",
      plainTitle: "정기 중심 흐름 QA와 비정기 비노출 확인",
      type: "story",
      group: "QA",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "C",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "핵심 사용자 시나리오 점검",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/63",
    },
    {
      id: "github-70",
      issueNumber: 70,
      title: "2-1-1 신청 접수 후 대기 상태 표시 정리",
      plainTitle: "신청 직후 대기 상태 표시",
      type: "task",
      group: "대기/잠금",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "기업 화면 상태 문구 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/70",
    },
    {
      id: "github-71",
      issueNumber: 71,
      title: "2-1-2 같은 시간대 추가 신청 차단 상태 정합성 점검",
      plainTitle: "같은 시간대 추가 신청 차단 확인",
      type: "task",
      group: "대기/잠금",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "차단 문구와 실제 상태 비교",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/71",
    },
    {
      id: "github-72",
      issueNumber: 72,
      title: "2-1-3 관리자/컨설턴트 화면 대기 상태 통일",
      plainTitle: "역할별 대기 상태 통일",
      type: "task",
      group: "대기/잠금",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "관리자/컨설턴트 화면 상태 뱃지 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/72",
    },
    {
      id: "github-73",
      issueNumber: 73,
      title: "2-2-1 72시간 경과 기준 정의 반영",
      plainTitle: "72시간 자동 확정 기준 시점 정의",
      type: "task",
      group: "자동 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "신청 접수 시점 기준인지 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/73",
    },
    {
      id: "github-74",
      issueNumber: 74,
      title: "2-2-2 미거절 신청 자동 확정 처리",
      plainTitle: "미거절 신청 자동 확정",
      type: "task",
      group: "자동 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "자동 확정 처리 방식 정리",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/74",
    },
    {
      id: "github-75",
      issueNumber: 75,
      title: "2-2-3 자동 확정 시 상태 표시 및 이력 반영",
      plainTitle: "자동 확정 표시와 이력 남기기",
      type: "task",
      group: "자동 확정",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "수동 확정과 구분되는 표시 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/75",
    },
    {
      id: "github-76",
      issueNumber: 76,
      title: "2-2-4 자동 확정 이후 Calendar/Gmail/Meet 후속 연동",
      plainTitle: "자동 확정 후 후속 연동",
      type: "task",
      group: "외부 연동",
      status: "todo",
      owner: "이지",
      startDate: "2026-04-23",
      endDate: "2026-05-14",
      stage: "A",
      outcome: "data-assets",
      output: "company-growth-platform",
      nextAction: "자동 확정 흐름에서도 일정/메일/미팅 연결 확인",
      url: "https://github.com/merryAI-dev/startup-diagnostic-platform/issues/76",
    },
  ],
  tools: [
    { id: "ax-admin", kind: "agent", label: "예산, 운영, 신청 관리 정리", phase: "operate" },
    { id: "ax-architect", kind: "agent", label: "자료 구조와 업무 흐름 설계", phase: "organize" },
    { id: "ax-builder", kind: "agent", label: "자동화와 화면 구현 지원", phase: "execute" },
    { id: "ax-researcher", kind: "agent", label: "인터뷰, 문서, 근거 분석", phase: "understand" },
    { id: "ax-storyteller", kind: "agent", label: "보고, 공유, 외부 발신 정리", phase: "share" },
    { id: "ax-publisher", kind: "agent", label: "배포, 전환, 운영 기준 정리", phase: "organize" },
    { id: "ax-infra-ops", kind: "skill", label: "Gmail, 예산, 인프라 점검", phase: "operate" },
    { id: "ax-tool-migration", kind: "skill", label: "기존 도구에서 새 도구로 옮기기", phase: "organize" },
    { id: "ax-deploy-guide", kind: "skill", label: "배포와 전환 절차 안내", phase: "execute" },
    { id: "ax-interview", kind: "skill", label: "인터뷰 진행과 정리", phase: "understand" },
    { id: "ax-show-tell", kind: "skill", label: "시연과 공유회 구성", phase: "share" },
    { id: "ax-restructure", kind: "skill", label: "Drive/Notion 자료 재구조화", phase: "organize" },
    { id: "ax-data-audit", kind: "skill", label: "데이터 누락, 중복, 품질 점검", phase: "organize" },
    { id: "ax-orchestrate", kind: "skill", label: "전체 작업 흐름 조율", phase: "all" },
  ],
  phases: [
    { id: "understand", title: "이해", subtitle: "문제와 자료 파악" },
    { id: "organize", title: "정리", subtitle: "정책과 구조 확정" },
    { id: "execute", title: "실행", subtitle: "운영 전환과 검증" },
  ],
  tokenUsage: {
    period: "2026-04-20/2026-04-24",
    updatedAt: "2026-04-24T14:20:00+09:00",
    totalTokens: 0,
    budgetTokens: 0,
    byProject: [
      { project: "startup-diagnostic-platform", label: "기업육성 플랫폼", tokens: 0, outputs: 21 },
      { project: "ax-dashboard", label: "AX 대시보드", tokens: 0, outputs: 1 },
    ],
  },
};
